<?php
/**
 * One-page installer. Delete this file once the panel is running.
 */
declare(strict_types=1);

define('INSTALLER', true);
require __DIR__ . '/app/bootstrap.php';

use App\Auth;
use App\Config;
use App\Database;
use App\Schema;
use App\Settings;

// Password provisioned for the first account. It is a bcrypt hash, so the
// plain password is never stored in the source tree.
const SEEDED_ADMIN_USERNAME = 'Dawood';
const SEEDED_ADMIN_HASH = '$2y$12$NNPgJd47rTATk/q/yJUfH.jBnxAAZz/7lE7j33FWTzazpdhzLM/v6';

$configPath = APP_DIR . '/config.php';
$alreadyInstalled = is_file($configPath);

$checks = [
    'PHP 8.0 or newer' => [PHP_VERSION_ID >= 80000, PHP_VERSION],
    'pdo_mysql extension' => [extension_loaded('pdo_mysql'), 'required for MySQL'],
    'mbstring extension' => [extension_loaded('mbstring'), 'required for text handling'],
    'json extension' => [extension_loaded('json'), 'required'],
    'Outbound HTTPS (curl or allow_url_fopen)' => [
        function_exists('curl_init') || filter_var(ini_get('allow_url_fopen'), FILTER_VALIDATE_BOOL),
        'required to reach api.openai.com',
    ],
    'app/ directory writable' => [is_writable(APP_DIR), APP_DIR],
    'storage/logs writable' => [is_writable(APP_ROOT . '/storage/logs'), APP_ROOT . '/storage/logs'],
];
$checksPass = !in_array(false, array_map(static fn (array $c): bool => (bool)$c[0], $checks), true);

$guessedBase = (function (): string {
    $scheme = App\Session::isHttps() ? 'https' : 'http';
    $host = $_SERVER['HTTP_HOST'] ?? 'localhost';
    $dir = rtrim(str_replace('\\', '/', dirname((string)($_SERVER['SCRIPT_NAME'] ?? '/'))), '/');
    return $scheme . '://' . $host . $dir;
})();

$errors = [];
$done = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$alreadyInstalled) {
    $db = [
        'host' => (string)post('db_host', 'localhost'),
        'name' => (string)post('db_name', ''),
        'user' => (string)post('db_user', ''),
        'pass' => (string)($_POST['db_pass'] ?? ''),
        'port' => (int)post('db_port', '3306'),
    ];
    $baseUrl = rtrim((string)post('base_url', $guessedBase), '/');
    $username = (string)post('admin_username', SEEDED_ADMIN_USERNAME);
    $password = (string)($_POST['admin_password'] ?? '');
    $email = post('admin_email') ?: null;

    if ($db['name'] === '' || $db['user'] === '') {
        $errors[] = 'Enter the database name and user you created in cPanel.';
    }
    if ($username === '') {
        $errors[] = 'Enter an admin username.';
    }
    if ($password !== '' && strlen($password) < 10) {
        $errors[] = 'The admin password must be at least 10 characters.';
    }
    if ($password === '' && $username !== SEEDED_ADMIN_USERNAME) {
        $errors[] = 'Enter a password for the admin account.';
    }

    if ($errors === []) {
        try {
            $pdo = Database::connect($db);
            Database::setPdo($pdo);
            Schema::migrate($pdo);

            $config = [
                'db' => $db,
                'base_url' => $baseUrl,
                'app_key' => bin2hex(random_bytes(32)),
                'session_name' => 'chatbotsid',
                'debug' => false,
            ];
            $written = file_put_contents(
                $configPath,
                "<?php\n// Generated by install.php - keep this file private.\nreturn " . var_export($config, true) . ";\n"
            );
            if ($written === false) {
                throw new RuntimeException('Could not write app/config.php. Give the app/ folder write permission (755) and try again.');
            }
            @chmod($configPath, 0640);
            Config::load($config);

            $existing = Database::value('SELECT id FROM users WHERE username = ?', [$username]);
            if ($existing === null) {
                if ($password === '') {
                    Database::run(
                        'INSERT INTO users (username, email, password_hash, role, must_change_password, created_at)
                         VALUES (?, ?, ?, ?, 1, NOW())',
                        [$username, $email, SEEDED_ADMIN_HASH, 'admin']
                    );
                } else {
                    Auth::createUser($username, $password, $email, false);
                }
            }

            Settings::put('schema_version', (string)Schema::VERSION);

            if (Settings::get('platform_name') === null) {
                Settings::put('platform_name', 'Chatbot Platform');
                Settings::put('default_chat_model', 'gpt-4o-mini');
                Settings::put('openai_base_url', 'https://api.openai.com/v1');
            }

            if (post('openai_api_key')) {
                Settings::put('openai_api_key', (string)post('openai_api_key'));
            }

            $done = true;
        } catch (Throwable $e) {
            $errors[] = $e->getMessage();
        }
    }
}
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>Install · Chatbot Platform</title>
<link rel="stylesheet" href="assets/admin.css">
</head>
<body>
<div class="auth-wrap" style="align-items:flex-start;padding:40px 20px">
  <div class="auth-card" style="max-width:640px">
    <h1>Install your chatbot platform</h1>
    <p class="sub">A two-minute setup for cPanel shared hosting.</p>

    <?php if ($alreadyInstalled): ?>
      <div class="alert success">
        This installation is already configured.
        <a href="index.php">Open the panel</a>.
      </div>
      <p class="muted">To reinstall, delete <span class="mono">app/config.php</span> first.
        For security, delete <span class="mono">install.php</span> from the server once you are done.</p>

    <?php elseif ($done): ?>
      <div class="alert success">Installation complete.</div>
      <p><strong>Two things left:</strong></p>
      <ol>
        <li>Delete <span class="mono">install.php</span> from the server.</li>
        <li>Sign in and add your OpenAI API key under Settings.</li>
      </ol>
      <a class="btn" href="index.php">Go to the panel</a>

    <?php else: ?>
      <?php foreach ($errors as $error): ?>
        <div class="alert error"><?= e($error) ?></div>
      <?php endforeach; ?>

      <h2 style="font-size:16px;margin-top:22px">Server check</h2>
      <table>
        <tbody>
        <?php foreach ($checks as $label => [$ok, $detail]): ?>
          <tr>
            <td><?= e($label) ?><br><span class="muted mono"><?= e((string)$detail) ?></span></td>
            <td class="right"><span class="badge <?= $ok ? 'green' : 'red' ?>"><?= $ok ? 'ok' : 'fix this' ?></span></td>
          </tr>
        <?php endforeach; ?>
        </tbody>
      </table>

      <form method="post" action="install.php" style="margin-top:24px">
        <h2 style="font-size:16px">Database</h2>
        <p class="muted" style="font-size:13px;margin-top:0">Create a database and user in cPanel → MySQL® Databases, give the user <em>all privileges</em>, then paste the details here.</p>
        <div class="field">
          <label for="db_host">Host</label>
          <input type="text" id="db_host" name="db_host" value="<?= e((string)post('db_host', 'localhost')) ?>">
        </div>
        <div class="field">
          <label for="db_name">Database name</label>
          <input type="text" id="db_name" name="db_name" value="<?= e((string)post('db_name', '')) ?>" placeholder="cpaneluser_chatbot" required>
        </div>
        <div class="field">
          <label for="db_user">Database user</label>
          <input type="text" id="db_user" name="db_user" value="<?= e((string)post('db_user', '')) ?>" placeholder="cpaneluser_chatbot" required>
        </div>
        <div class="field">
          <label for="db_pass">Database password</label>
          <input type="password" id="db_pass" name="db_pass" autocomplete="off">
        </div>
        <div class="field">
          <label for="db_port">Port</label>
          <input type="number" id="db_port" name="db_port" value="<?= e((string)post('db_port', '3306')) ?>">
        </div>

        <h2 style="font-size:16px;margin-top:22px">This installation</h2>
        <div class="field">
          <label for="base_url">Public URL</label>
          <input type="text" id="base_url" name="base_url" value="<?= e((string)post('base_url', $guessedBase)) ?>">
          <div class="help">Used to build the embed code.</div>
        </div>

        <h2 style="font-size:16px;margin-top:22px">Admin account</h2>
        <div class="field">
          <label for="admin_username">Username</label>
          <input type="text" id="admin_username" name="admin_username" value="<?= e((string)post('admin_username', SEEDED_ADMIN_USERNAME)) ?>" required>
        </div>
        <div class="field">
          <label for="admin_password">Password</label>
          <input type="password" id="admin_password" name="admin_password" autocomplete="new-password" minlength="10">
          <div class="help">Leave empty to keep the password that was already set up for <strong><?= e(SEEDED_ADMIN_USERNAME) ?></strong>; you will be asked to change it at first sign-in.</div>
        </div>
        <div class="field">
          <label for="admin_email">Email (optional)</label>
          <input type="email" id="admin_email" name="admin_email" value="<?= e((string)post('admin_email', '')) ?>">
        </div>

        <h2 style="font-size:16px;margin-top:22px">OpenAI (optional now)</h2>
        <div class="field">
          <label for="openai_api_key">API key</label>
          <input type="password" id="openai_api_key" name="openai_api_key" autocomplete="off" placeholder="sk-…">
          <div class="help">You can also add it later under Settings.</div>
        </div>

        <button class="btn" type="submit" style="width:100%;justify-content:center" <?= $checksPass ? '' : 'disabled' ?>>
          <?= $checksPass ? 'Install now' : 'Fix the items above first' ?>
        </button>
      </form>
    <?php endif; ?>
  </div>
</div>
</body>
</html>
